### ISSUE TITLE
[py.dae] TODO

### ISSUE THREAD

**Issue by dthierry** [dthierry/nmpc_mhe_q#8]
- [ ] Create reasonable unittest for all the framework
- [ ] Implement the .clone() strategy throughout the whole framework
- [ ] Deal with the steady-state problem. *fetch dvars*, *dvars==0*, *delete collocation equations*, *delete initial conditions*
- [ ] Dummy param vs fixed var for the input
